KunstmaanAdminBundle_default:
    resource: '@KunstmaanAdminBundle/Controller/DefaultController.php'
    type:     annotation
    prefix:   /%kunstmaan_admin.admin_prefix%

KunstmaanAdminBundle_modules:
    resource: '@KunstmaanAdminBundle/Controller/ModulesController.php'
    type:     annotation
    prefix:   /%kunstmaan_admin.admin_prefix%/modules

KunstmaanAdminBundle_settings:
    resource: '@KunstmaanAdminBundle/Controller/SettingsController.php'
    type:     annotation
    prefix:   /%kunstmaan_admin.admin_prefix%/settings

# Change user password route
KunstmaanAdminBundle_user_change_password:
    path: /%kunstmaan_admin.admin_prefix%/settings/users/{id}/edit
    defaults: { _controller: FOSUserBundle:ChangePassword:changePassword }
    methods: [GET, POST]

###########################
## fos_userbundle routes ##
###########################

fos_user_security_login:
    path: /%kunstmaan_admin.admin_prefix%/login
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    path: /%kunstmaan_admin.admin_prefix%/login_check
    defaults: { _controller: FOSUserBundle:Security:check }

fos_user_security_logout:
    path: /%kunstmaan_admin.admin_prefix%/logout
    defaults: { _controller: FOSUserBundle:Security:logout }

fos_user_profile:
    resource: '@FOSUserBundle/Resources/config/routing/profile.xml'
    prefix: /%kunstmaan_admin.admin_prefix%/profile

fos_user_resetting:
    resource: '@FOSUserBundle/Resources/config/routing/resetting.xml'
    prefix: /%kunstmaan_admin.admin_prefix%/resetting

fos_user_change_password:
    path: /%kunstmaan_admin.admin_prefix%/profile/change-password
    defaults: { _controller: FOSUserBundle:ChangePassword:changePassword }
    methods: [GET, POST]

##########################
## Google OAuth Sign In ##
##########################
KunstmaanAdminBundle_oauth_signin:
    path: /%kunstmaan_admin.admin_prefix%/google_signin_check
    defaults: { _controller: KunstmaanAdminBundle:OAuth:check }
