KunstmaanAdminBundle_default:
    resource: '@KunstmaanAdminBundle/Controller/DefaultController.php'
    type:     annotation
    prefix:   /admin  

KunstmaanAdminBundle_modules:
    resource: '@KunstmaanAdminBundle/Controller/ModulesController.php'
    type:     annotation
    prefix:   /admin/modules
        
KunstmaanAdminBundle_settings:
    resource: '@KunstmaanAdminBundle/Controller/SettingsController.php'
    type:     annotation
    prefix:   /admin/settings      

# Change user password route
KunstmaanAdminBundle_user_change_password:
    path: /admin/settings/users/{id}/edit
    defaults: { _controller: FOSUserBundle:ChangePassword:changePassword }
    methods: [GET, POST]

###########################
## fos_userbundle routes ##
###########################

fos_user_security_login:
    path: /admin/login
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    path: /admin/login_check
    defaults: { _controller: FOSUserBundle:Security:check }
        
fos_user_security_logout:
    path: /admin/logout
    defaults: { _controller: FOSUserBundle:Security:logout }

fos_user_profile:
    resource: '@FOSUserBundle/Resources/config/routing/profile.xml'
    prefix: /admin/profile

fos_user_resetting:
    resource: '@FOSUserBundle/Resources/config/routing/resetting.xml'
    prefix: /admin/resetting

fos_user_change_password:
    path: /admin/profile/change-password
    defaults: { _controller: FOSUserBundle:ChangePassword:changePassword }
    methods: [GET, POST]

##########################
## Google OAuth Sign In ##
##########################
KunstmaanAdminBundle_oauth_signin:
    path: /admin/google_signin_check
    defaults: { _controller: KunstmaanAdminBundle:OAuth:check }
