nelmio_api_doc:
  documentation:
    definitions:

      Node:
        title: "Node"
        type: "object"
        properties:
          id:
            type: "integer"
          hidden_from_nav:
            type: "boolean"
          ref_entity_name:
            type: "string"
          internal_name:
            type: "string"

      NodeTranslation:
        properties:
          title:
            type: "string"
          lang:
            type: "string"
          online:
            type: "boolean"

      ApiPage:
        title: "Page"
        type: "object"
        properties:
          page:
            type: "object"
            allOf:
              - $ref: '#/definitions/ApiEntity'
          pageTemplate:
            type: "object"
            allOf:
              - $ref: '#/definitions/ApiPageTemplate'
          node:
            type: "object"
            allOf:
              - $ref: '#/definitions/PostNode'
          nodeTranslation:
            type: "object"
            allOf:
              - $ref: '#/definitions/PostNodeTranslation'

      GetNode:
        allOf:
          - $ref: '#/definitions/Node'
          - properties:
              parent:
                type: "object"
                allOf:
                  - $ref: '#/definitions/Node'
      PostNode:
        allOf:
          - $ref: '#/definitions/Node'
          - properties:
              parent:
                type: "object"
                allOf:
                  - $ref: '#/definitions/Node'

      NodeTranslation:
        allOf:
          - $ref: '#/definitions/NodeTranslation'
          - properties:
              id:
                type: "integer"
              weight:
                type: "integer"
              created:
                type: "string"
                format: "date-time"
              updated:
                type: "string"
                format: "date-time"

      PostNodeTranslation:
         allOf:
          - $ref: '#/definitions/NodeTranslation'

      NodeVersion:
        title: "nodeVersion"
        type: "object"
        properties:
          id:
            type: "integer"
          owner:
            type: "id"
          ref_id:
            type: "integer"
          ref_entity_name:
            type: "string"

      NodeList:
        title: "NodeList"
        type: "array"
        items:
          allOf:
            - $ref: '#/definitions/GetNode'

      ApiEntity:
        title: "ApiEntity"
        type: "object"
        properties:
          type:
            type: "string"
            example: 'Kunstmaan\SomeBundle\Entity\Pages\HomePage'
          data:
            type: "object"

      ApiPagePart:
        title: "ApiPagePart"
        type: "object"
        properties:
          type:
            type: "string"
          data:
            type: "object"

      ApiContext:
        title: "ApiContext"
        type: "object"
        properties:
          name:
            type: "string"
          pageparts:
            type: "array"
            items:
              allOf:
                - $ref: '#/definitions/ApiPagePart'

      ApiPageTemplate:
        title: "ApiPageTemplate"
        type: "object"
        properties:
          name:
            type: "string"
          contexts:
            type: "array"
            items:
              allOf:
                - $ref: '#/definitions/ApiContext'

      GetApiPage:
        allOf:
          - $ref: '#/definitions/ApiPage'
          - properties:
            nodeVersion:
              type: "object"
              allOf:
                - $ref: '#/definitions/NodeVersion'

      PostApiPage:
        allOf:
          - $ref: '#/definitions/ApiPage'

      PutApiPage:
        allOf:
          - $ref: '#/definitions/ApiPage'
