language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    # Test LTS versions. This makes sure we do not use Symfony packages with version greater than 3. Read more at https://github.com/symfony/lts
    - php: 7.3
      env: DEPENDENCIES="symfony/lts:^3"

    - php: 7.1
    - php: 7.2
      env: COVERAGE=true CODECEPTION_FLAGS="--coverage --coverage-xml"
    - php: 7.3

before_install:
  - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
  - echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --no-update; fi
  - wget https://scrutinizer-ci.com/ocular.phar
  - nvm install
  - npm install
  - export SYMFONY_DEPRECATIONS_HELPER=weak
  # Remove any twig syntax from the groundcontrol package.json
  - sed -i -e 's/{% if demosite %}//g' src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/package.json
  - sed -i -e 's/{% endif %}//g' src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/package.json
  - sed -i -e 's/"name".*/"name":"demo",/g' src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/package.json
  - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;

install:
  - composer update --prefer-dist $COMPOSER_FLAGS

script: ./vendor/codeception/codeception/codecept run $CODECEPTION_FLAGS

after_script:
    - php ocular.phar code-coverage:upload --format=php-clover _output/coverage.xml
    - npm run build -- --continueAfterTestError=true
    - npm run buildGroundControlSkeleton

notifications:
  email:
    - travis@kunstmaan.be
