language: php

cache:
  directories:
    - $HOME/.composer/cache/files

addons:
  apt:
    packages:
      - ghostscript

env:
  global:
    - PHPUNIT_FLAGS="-v"
    - SYMFONY_DEPRECATIONS_HELPER="max[self]=0"

before_install:
  - yes | pecl install imagick
  - sudo sed -i -e 's/<policy domain="coder" rights="none" pattern="PDF" \/>/<policy domain="coder" rights="read|write" pattern="PDF" \/>/' /etc/ImageMagick-6/policy.xml
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - travis_retry composer self-update
  - composer global require symfony/flex

install:
  - composer update $COMPOSER_FLAGS --prefer-dist --no-progress --no-suggest --ansi

before_script:
  - |
    if [[ $COVERAGE = true ]]; then
      mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
      if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
    fi

script: ./vendor/bin/phpunit $PHPUNIT_FLAGS

after_script:
  - |
    if [[ $COVERAGE = true ]]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      travis_retry php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi

jobs:
  include:
    # Test lowest dependencies
    - stage: Test
      php: 7.1
      env:
        - SYMFONY_REQUIRE='^3.4'
        - COMPOSER_FLAGS="--prefer-lowest"
        - SYMFONY_DEPRECATIONS_HELPER="max[direct]=1" # Workaround for BC layer triggering a deprecation in Group entity

    # Test latest php with LTS versions.
    - stage: Test
      php: 7.3
      env: SYMFONY_REQUIRE='^3.4'
    - stage: Test
      php: 7.3
      env: SYMFONY_REQUIRE='^4.4'

    # Test the latest stable release
    - stage: Test
      php: 7.1
    - stage: Test
      php: 7.2
    - stage: Test
      php: 7.3
    - stage: Test
      php: 7.4
      env:
        - COVERAGE=true
        - PHPUNIT_FLAGS="-v --coverage-clover=coverage.clover"

    - stage: Test
      php: 7.4
      env:
        - COMPOSER_VALIDATE=true
      before_install: skip
      install: skip
      before_script: skip
      script: sh ./.build/validate-composer.sh || exit $?;
      after_script: skip

    # Validate frontend setup
    - stage: Test
      language: javascript
      cache:
        npm: false
      before_install:
        # Remove any twig syntax from the groundcontrol package.json
        - sed -i -e 's/{% if demosite %}//g' src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/package.json
        - sed -i -e 's/{% endif %}//g' src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/package.json
        - sed -i -e 's/"name".*/"name":"demo",/g' src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/package.json
      install:
        - npm install
      before_script: skip
      script:
        - npm run build -- --continueAfterTestError=true
        - npm run buildGroundControlSkeleton
      after_script: skip

    # Code quality checks
    - stage: Code quality
      php: 7.4
      env: PHPStan=true
      script: vendor/bin/phpstan analyse --no-progress


