language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true
  allow_failures: ~

before_install:
  - phpenv config-rm xdebug.ini || true
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --no-update; fi
  - wget https://scrutinizer-ci.com/ocular.phar

install: composer update --prefer-dist $COMPOSER_FLAGS

before_script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ $(php -r "echo PHP_MINOR_VERSION;") -le 4 ] && [ $(php -r "echo PHP_MAJOR_VERSION;") -le 5 ]; then echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ $(php -r "echo PHP_MAJOR_VERSION;") -le 5 ]; then echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ $(php -r "echo PHP_MAJOR_VERSION;") -le 5 ]; then echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;

script: ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script: php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email:
    - travis@kunstmaan.be
