language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  - SYMFONY_VERSION="2.6.*"

matrix:
  fast_finish: false
  allow_failures:
    - php: 7.0
  include:
    - php: 5.6
      env: SYMFONY_VERSION="2.5.*"
    - php: 5.6
      env: SYMFONY_VERSION="2.3.*"

before_script:
    - composer selfupdate
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then echo "" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini; fi;'
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ] && [ $(php -r "echo PHP_MINOR_VERSION;") -le 4 ]; then echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;'
    - composer require symfony/symfony:${SYMFONY_VERSION}
    - wget https://scrutinizer-ci.com/ocular.phar

script:
    - ./vendor/bin/phpunit --coverage-clover=coverage.clover
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email:
    - travis@kunstmaan.be
