services:
{% if demosite %}
    {{ bundle.name|lower }}.bikes.twig.extension:
        class: {{ bundle.namespace }}\Twig\BikesTwigExtension
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: twig.extension }
{% endif %}
