KunstmaanNodeBundle_widgets:
    resource: '@KunstmaanNodeBundle/Controller/WidgetsController.php'
    type:     annotation
    prefix:   /%kunstmaan_admin.admin_prefix%/nodewidgets

KunstmaanNodeBundle_nodes:
    resource: '@KunstmaanNodeBundle/Controller/NodeAdminController.php'
    type:     annotation
    prefix:   /%kunstmaan_admin.admin_prefix%/nodes

KunstmaanNodeBundle_urlchooser_replace:
    prefix:   /%kunstmaan_admin.admin_prefix%/url-replace
    path: /replace
    defaults: { _controller: kunstmaan_node.url_replace.controller:replaceURLAction }
