parameters:
    kunstmaan_search.transformers.nodetransformerclass: Kunstmaan\SearchBundle\Transformers\NodeTransformer
    kunstmaan_search.website_custom_mappings:
        content:
            handlerclass: Kunstmaan\AdminNodeBundle\Entity\NodeTranslation
            handlermethod: getSearchContentForNode


foq_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        website:
            client: default
            types:
                page:
                    mappings:
                        title:
                        id:
                        content: { analyzer: snowball }
                    persistence:
                        driver: orm
                        provider:
                        model: Kunstmaan\AdminNodeBundle\Entity\NodeTranslation
                        model_to_elastica_transformer:
                            service: kunstmaan_search.transformers.nodetransformer
                        listener:
                        finder:
