Kunstmaan\NodeBundle\Entity\NodeTranslation:
    exclusion_policy: ALL
    properties:
        lang:
            expose: true
        online:
            expose: true
        title:
            expose: true
        weight:
            expose: true
        created:
            expose: true
        updated:
            expose: true
