Kunstmaan\Rest\NodeBundle\Model\ApiPageTemplate:
  exclusion_policy: ALL

  properties:
    name:
      expose: true
      type: string
      groups: [edit]

    contexts:
      expose: true
      type: 'array<Kunstmaan\Rest\NodeBundle\Model\ApiContext>'
      groups: [edit]
