

{{ bundle.getName()|lower }}_{{ entity_class|lower }}page_admin_list:
    resource: @{{ bundle.getName() }}/Controller/{{ entity_class }}PageAdminListController.php
    type:     annotation
    prefix:   /admin/{{ entity_class|lower }}page/

{{ bundle.getName()|lower }}_{{ entity_class|lower }}author_admin_list:
    resource: @{{ bundle.getName() }}/Controller/{{ entity_class }}AuthorAdminListController.php
    type:     annotation
    prefix:   /admin/{{ entity_class|lower }}author/
