

{{ bundle.getName()|lower }}_{{ entity_class|lower }}page_admin_list:
    resource: @{{ bundle.getName() }}/Controller/{{ entity_class }}PageAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/{{ entity_class|lower }}page/
    requirements:
         _locale: %requiredlocales%

{{ bundle.getName()|lower }}_{{ entity_class|lower }}author_admin_list:
    resource: @{{ bundle.getName() }}/Controller/{{ entity_class }}AuthorAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/{{ entity_class|lower }}author/
    requirements:
         _locale: %requiredlocales%