services:
    kunstmaan_languagechooser.languagechooserrouter:
        class: Kunstmaan\LanguageChooserBundle\Router\LanguageChooserRouter
        arguments: ["@service_container"]
        tags:
            - { name: router, priority: 100 }

    twig.extension.your_extension_name:
        class: Kunstmaan\LanguageChooserBundle\Twig\Extension\LanguageChooserExtension
        calls:
             - [setLanguageChooserLanguages, [%kunstmaan_language_chooser.languagechooserlocales%]]
        tags:
            - { name: twig.extension }

    kunstmaan_languagechooser.url_locale_guesser:
        class: Kunstmaan\LanguageChooserBundle\LocaleGuesser\UrlLocaleGuesser
        arguments: ["@lunetics_locale.validator.meta"]
        tags:
            - { name: lunetics_locale.guesser, alias: kuma_url_guesser }
