parameters:
    kunstmaan_adminlist.service.export.class: Kunstmaan\AdminListBundle\Service\ExportService

services:
    kunstmaan_adminlist.factory:
        class: Kunstmaan\AdminListBundle\AdminList\AdminListFactory

    kunstmaan_adminlist.service.export:
        class:  %kunstmaan_adminlist.service.export.class%
        calls:
            -  [ setRenderer, [ "@templating" ] ]

    kunstmaan_adminlist.twig.extension:
        class: Kunstmaan\AdminListBundle\Twig\AdminListTwigExtension
        tags:
            -  { name: twig.extension }
        arguments:
            -  @service_container
