services:
    # Autowire aliases
    Kunstmaan\AdminListBundle\AdminList\AdminListFactory: '@kunstmaan_adminlist.factory'
    Kunstmaan\AdminListBundle\Service\ExportService: '@kunstmaan_adminlist.service.export'
    Kunstmaan\AdminListBundle\Service\EntityVersionLockService: '@kunstmaan_entity.admin_entity.entity_version_lock_service'

    kunstmaan_adminlist.factory:
        class: Kunstmaan\AdminListBundle\AdminList\AdminListFactory
        public: true

    kunstmaan_adminlist.service.export:
        class: Kunstmaan\AdminListBundle\Service\ExportService
        arguments:
            - '@twig'
            - '@translator'
        public: true

    kunstmaan_adminlist.twig.extension:
        class: Kunstmaan\AdminListBundle\Twig\AdminListTwigExtension
        tags:
            -  { name: twig.extension }

    kunstmaan_entity.admin_entity.entity_version_lock_service:
        class: Kunstmaan\AdminListBundle\Service\EntityVersionLockService
        arguments:
            -  '@doctrine.orm.entity_manager'
            -  '%kunstmaan_entity.lock_threshold%'
            -  '%kunstmaan_entity.lock_enabled%'

    kunstmaan_adminlist.subscriber.adminlist:
        class: Kunstmaan\AdminListBundle\EventSubscriber\AdminListSubscriber
        arguments:
            - "@router"
        tags:
            - { name: kernel.event_subscriber }
