liip_imagine:
    cache_prefix: uploads/cache
    driver: imagick
    data_loader: kunstmaan_media_thumbloader
    #cache: no_cache
    filter_sets:
        media_list_thumbnail:
            quality: 75
            filters:
                thumbnail: { size: [210, 150], mode: inset }
        media_detail_thumbnail:
            quality: 75
            filters:
                thumbnail: { size: [700, 500], mode: inset }
