KunstmaanTranslatorBundle_translations:
    resource: "@KunstmaanTranslatorBundle/Controller/TranslatorController.php"
    type:     annotation
    prefix:   /admin/settings/translations

KunstmaanTranslatorBundle_translations_commands:
    resource: "@KunstmaanTranslatorBundle/Controller/TranslatorCommandController.php"
    type:     annotation
    prefix:   /admin/settings/translations

#KunstmaanTranslatorBundle_settings_translations_add:
#    pattern:   /add/{domain}/{locale}/{keyword}
#    defaults:  { _controller: KunstmaanTranslatorBundle:Translator:add, domain: '', locale:'%defaultlocale%', keyword: '' }
#
#KunstmaanTranslatorBundle_settings_translations_edit_search:
#    pattern:   /add/{domain}/{locale}/{keyword}
#    defaults:  { _controller: KunstmaanTranslatorBundle:Translator:editSearch, domain: '', locale:'%defaultlocale%', keyword: '' }
